// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmzirtsdocqdbmfqdnub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtemlydHNkb2NxZGJtZnFkbnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NjE2MDYsImV4cCI6MjA3MDQzNzYwNn0.spcXi5GZgnpHdc6VbRruAgoWRH494nlDyMQQiKzwXoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});